### ISSUE TITLE
Transparency / Newest Spine doesn't work

### ISSUE THREAD

**Issue by Lgood20** [jeremyfa/spine-hx#18]
Hey Jeremy,

I'm having some issues with the latest build of Spine for Stencyl. It doesn't seem to handle Opacity or Transparency that well. I have attached a screen shot of it in Spine, and one in Stencyl. See how the one in Stencyl has the transparency as Black, and when the gold fades in spine, it doesn't fade in Stencyl.

Also, it doesn't seem to register the latest version of Spine for Stencyl.

Not sure of I'm doing something wrong, but was wondering how I could fix it.

Cheers,

Lindsay
![2019-12-15_19h15_54](https://user-images.githubusercontent.com/52391978/72214785-b6e1d580-3554-11ea-92d4-5c443f12bbac.png)
![78784115_1964378220375423_6064576689051009024_n](https://user-images.githubusercontent.com/52391978/72214786-b6e1d580-3554-11ea-8ca0-7df821434e22.jpg)

**Comment by jeremyfa** [comment]
Hi, unfortunately there is not much I can do here. The issue seems to be related to Stencyl integration, which is outside of the scope of the repository I maintain: just the runtime.

All I can say is that alpha is expected to work. I am using it extensively (not with Stencyl) without any issues on my side.

I guess you should try to reach people maintaining the spine renderer for Stencyl.
