### ISSUE TITLE
Updating to use Haxe 4

### ISSUE THREAD

**Issue by jrdoughty** [jeremyfa/spine-hx#27]
What would it take to update to Haxe 4? I'd like to take a crack at it, but want to know what I'm getting myself into.

**Comment by jeremyfa** [comment]
The runtime is already compatible with Haxe 4.

Only the converter depends on Haxe 3.

It’s tricky to update the converter to Haxe 4 because it uses compiler errors to auto-fix issues in the generated haxe code base, and updating the converter to Haxe 4 would mean updating the part that treats those haxe compiler error messages, which are slightly different in haxe 4.

Anyway, why would you want to do that? It doesn’t really matter with which Haxe version the runtime is generated, as long as that generated code can run with Haxe 4 and above

**Comment by jrdoughty** [comment]
Primarily the reason I'd considered it was because a friend and I are looking at doing a project and he pointed out that he wasn't sure if he'd need additional setups of haxe to work with Spine in it. Sounds like its fairly trivial of a requirement? I'd be good to be on 4 from an upkeep perspective, but I don't know if its worth it or not. I'll have to look into how many of those errors you'd have to work with. The other dev and I though have shifted to a non-sprite project, so it may take a bit before I can dive in. I'll close this since I think your answer gives me a strong inclination what I'd have to look into.

**Comment by jeremyfa** [comment]
You don't need any specific version of haxe if you just want to use spine runtime, as long as haxe version is 3.2 or higher (including haxe 4.x+).

Normally you won't need to use the converter yourself as the runtime is already converted and ready to use, so that sounds like a non-issue?

**Comment by jrdoughty** [comment]
Oh ok, then yeah it sounds like a non-issue!
